title: Vladimir Samoylov # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Chief Information Officer
  <br><br>
  The main goal at the moment for myself I consider the structuring of all acquired knowledge and experience through self-education.
  I really dream of working in a real IT company, where I can fully realize my skillset.
  <br><br>
  <a href="https://www.linkedin.com/in/vladimirsamoylov/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
