baseURL = "https://cageyv.dev/"
title = "Vladimir Samoylov"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

enableRobotsTXT = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Vladimir Samoylov"
    description = "Vladimir Samoylov's personal website"
    keywords = "devops,k8s,aws,terraform,cloud,developer,personal"
    info = "Cloud Engineer and Independent consultant"
    avatarURL = "images/avatar.webp"
    #gravatar = "john.doe@example.com"
    footerContent = "Hosted on GitHub Pages."

    dateFormat = "January 2, 2006"

    hideFooter = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/cageyv/cageyv.github.io/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
	  childsrc = ["'self'"]
	  fontsrc = [
            "'self'",
		    "https://fonts.gstatic.com",
		    "https://cdn.jsdelivr.net/"
      ]
	  formaction = ["'self'"]
	  framesrc = ["'self'"]
	  imgsrc = [
          "'self'",
          "https://cdnjs.cloudflare.com/ajax/libs/photoswipe/"
      ]
	  objectsrc = ["'none'"]
	  stylesrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://cdn.jsdelivr.net/",
            "https://cdnjs.cloudflare.com/ajax/libs/photoswipe/"
      ]
	  scriptsrc = [
        "'self'",
		    "'unsafe-inline'",
            "https://code.jquery.com/",
            "https://cdnjs.cloudflare.com/ajax/libs/photoswipe/",
            "https://twemoji.maxcdn.com",
            "https://static.cloudflareinsights.com/"
      ]
      connectsrc = [
          "'self'"
      ]
	  prefetchsrc = ["'self'"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/cageyv/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/cageyv/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/vladimirsamoylov/"
[[params.social]]
    name = "Telegram"
    icon = "fa fa-telegram"
    weight = 5
    url = "https://t.me/cageyv/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 6
    url = "https://twitter.com/cageyvdev"    
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 7
    url = "https://cadeyv.dev/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[[params.badges]]
name = "AWS Community Builder"
img = "images/aws-community-builders.webp"
weight = 1
url = "https://aws.amazon.com/developer/community/community-builders/community-builders-directory/?cb-cards.sort-by=item.additionalFields.cbName&cb-cards.sort-order=asc&awsf.builder-category=*all&awsf.location=*all&awsf.year=*all&cb-cards.q=Samoylov%2BVladimir&cb-cards.q_operator=AND"

[[params.badges]]
name = "AWS Solutions Architect Professional"
img = "images/aws-certified-solutions-architect-professional.webp"
weight = 2
url = "https://www.credly.com/badges/29dfa08e-4ebd-46e7-a7e9-d3ff52aa80be/public_url"

[[params.badges]]
name = "HashiCorp Terraform Assocaiate"
img = "images/hashicorp-certified-terraform-associate.webp"
weight = 3
url = "https://www.credly.com/badges/096e9341-0ff8-4568-ab17-b2da022dd6dc/public_url"

[[params.badges]]
name = "AWS Solutions Architect Assocaiate"
img = "images/aws-certified-solutions-architect-associate.webp"
weight = 4
url = "https://www.credly.com/badges/321e975e-ef89-404e-ad6e-63db23d21f27/public_url"

[[params.badges]]
name = "Certified ScrumMaster (CSM)"
img = "images/seal-csm.webp"
weight = 5
url = "https://bcert.me/puwvubqw"

[[params.badges]]
name = "AWS Certified Cloud Practitioner"
img = "images/aws-certified-cloud-practitioner.webp"
weight = 6
url = "https://www.credly.com/badges/b80c3f21-5cf9-4fd5-a27a-b672cf0b80fd/public_url "

[[params.badges]]
name = "Fivexl"
img = "images/fivexl.webp"
weight = 7
url = "https://fivexl.io/author/vladimir-samoylov/"

[[params.badges]]
name = "DevWithAI"
img = "images/badge-dev-with-ai.webp"
weight = 8
url = "https://cageyv.dev/"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Experience"
            weight = 3
            url = "experience/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 4
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Education"
            weight = 5
            url = "education/"

            [[languages.en.menu.main]]
            name = "Recommend"
            weight = 6
            url = "recommend/"

